name: Sentry Sourcemaps

on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  sentry-sourcemaps:
    uses: SirPaulO/tavolai-contracts/.github/workflows/reusable-sentry-sourcemaps.yml@main
    secrets: inherit
